apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efspihole
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-pihole
  resources:
    requests:
      storage: 5Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efsdnsmasq
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-dnsmasq
  resources:
    requests:
      storage: 5Gi
